### ISSUE TITLE
改ページのルール改善

### ISSUE THREAD

**Issue by yuluji** [structuralengine/FramePrintPDF#62]
現状は、①指定の行数になった場合、②Caseが変わった場合
にどちらかに該当するとき、改ページを行っている。
ただし、②で計算のパターンが変わっても、行数が少なく、ページ内に収まる場合は改ページを行わない処理を行っている。

しかし、①では改ページのタイミングが統一されておらず、ページによって下部のスペースがばらばらである。
①で改ページする場合は指定号数ではなくてページ下端からの距離などで判定したい。

![①指定行数で改行](https://user-images.githubusercontent.com/109077766/207506829-b2c51736-660a-48f6-aa9c-ca012e3d2fe2.png)
△①の改ページ

![②計算ケースが変わって改行](https://user-images.githubusercontent.com/109077766/207507182-4f4411d0-444d-4b60-ad42-16add01d40af.png)
△②の改ページ

**Comment by yuluji** [comment]
サンプルデータ
[FrameWebForJS.pdf](https://github.com/structuralengine/FramePrintPDF/files/10224332/FrameWebForJS.pdf)
△出力PDF

[frameWebForJS.1.zip](https://github.com/structuralengine/FramePrintPDF/files/10224335/frameWebForJS.1.zip)
△入力値のJsonファイル
※立体骨組解析でファイルを開くから実行可能

**Comment by sasaco** [comment]
CWに依頼した時
「断面力図は、改ページルールを除外してください」
とお願いしたところ
断面力図を作成する機能をコメントアウトしてしまった
#66 で 断面力図を作成する機能を復活しました
![image](https://user-images.githubusercontent.com/4043298/211761107-e85f23dd-09d2-49e5-8cae-697758c2b55d.png)
